apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: team-fraud-detection
  namespace: argocd
spec:
  description: team-fraud-detection's own Applications only
  sourceRepos:
    - https://gitlab.com/demo-org/helm-charts.git
    - https://gitlab.com/demo-org/fraud-detection-demo.git
  destinations:
    - server: https://kubernetes.default.svc
      namespace: team-fraud-detection
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
